export const GET_MEN_PRODUCTS_REQUEST = "GET_MEN_PRODUCTS_REQUEST";
export const GET_MEN_PRODUCTS_SUCCESS = "GET_MEN_PRODUCTS_SUCCESS";
export const GET_MEN_PRODUCTS_FAILURE = "GET_MEN_PRODUCTS_FAILURE";